version: '3'

services:
  nginx:
    image: docker.io/linuxserver/swag
    container_name: nginx
    environment:
      - PUID=1000            # Your user ID
      - PGID=1000            # Your group ID
      - TZ=Europe/London           # Your timezone
      - URL=wip.parkerbritt.com  # Replace with your domain
      - SUBDOMAINS=       # Subdomains to cover
      - VALIDATION=http      # Validation method
    volumes:
      - ./pages:/config/www:ro
      - ./css:/config/www/css:ro
      - ./assets:/config/www/assets:ro
      - ./js:/config/www/js:ro
      - ./components:/config/www/components:ro
      - ./nginx_prod.conf:/etc/nginx/nginx.conf:ro
      - ./swag_config:/config
    ports:
      - "8000:80"
      - "4430:443"
    restart: unless-stopped
